### PR TITLE
Feature/touch up ohms styling

### PR DESCRIPTION
**Pull request by boveus**
This PR addresses the styling changes that @jonmbodnar requested:

```
Index View

Search results list items lose border (border should stay, hover or not)
Repeated clicking on a search result item does not change associated index item heading's +/- icon—it stays as a minus (-) whether opened or closed
Index view: Set link to `display:block` so that entire transcript index heading is clickable, rather than just link text and +/- icon
Set .panel-title > a to display:block to make entire width of the .panel-title heading clickable, not just the link text and the +/- icon.
When a user clicks the "play segment" button on an indexed oral history the oral history video should immediately start playing, even if paused.
Index view: Troubleshoot odd interactions with search results and show/hide on panels. Sometimes don't open or if open don't close. Bascially, clicking a new heading or on a search result that targets a panel other than one that is already open should close all open index panels and set all their icons to plus and then open the targeted panel and set its icon to minus, to eliminate confusing interactions.
Transcript View

Search results list items lose border (border should stay, hover or not)
```
I think I covered all of them, but please let me know if there are any issues.

I removed the 'btn-link' class from the search results.  It was causing the border to disappear on hover.  Instead of using the btn-link class I just added some css for the search results to make them appear consistently with other hyperlinks.

I modified the youtube JS logic so that it plays the video on click.  This was an easy change, but it took me a little while to find where the event listener was so I added a comment for that section of the code.

I also changed how the oral history indexed transcript JS is working in regards to hiding/showing the panels.  I simplified the code a lot by making the event listeners for the collapse/show events the only place that modifies the plus-minus-icon element.  That makes it a lot easier to deal with.  Before this change the 'collapseAllPanels' function was also modifying that elements state.   I also changed the jquery `toggleClass` function to  `.removeClass('glyphicon-plus').addClass('glyphicon-minus');`  instead.  I felt like the toggleClass option wasn't explicit enough and may have resulted in some unintended behavior (a panel having a + when it is open or a - when it is closed).  

I modified the CSS a bit to account for some of those changes, but the CSS should be pretty explanatory.

### CODE REVIEW

**Comment by jonmbodnar** [comment]
Changing the link in .panel-... to display block creates a global problem. It affects all panel group headings/icons across the application.  See the attached screenshot for an example.
 
screen shot 2018-08-03 at 8 55 09 am

You and Eric may want to rethink the implementation. I'd also suggest you two consider refactoring the markup to clean it up, find a way to eliminate the need to nest so many panel groups. 

We also have an issue if you run a search in an index view and get two results that are both from the same index panel. Clicking the first result opens the panel. Clicking the second closes the panel. From a user perspective it's unclear what's happening and why.

Hovering over a link works. The border stays. We can talk.

**Comment by boveus** [comment]
hey guys, I added some comments and refactored some of the code so it is more clear what is happening.  I added a few functions that will determine if the search result is already open and, if so, it won't close the tab when the user clicks on it.

Additionally, I noticed some inconsistency with how the scroll to top animation was working.  It would work as expected if there was an open panel and a user clicked on a result for a panel that was higher up on the list.  If the user clicked on a result that was lower on the list it would scroll slightly below the header of the element.  The reason this was happening is because the show and hide panel events occur immediately, so the offsetTop was being calculated as soon as the panel had a show or hide event happen.  

To fix this issue I moved the animation to be inside the event listener that listens for the "shown" event.  This listener will only fire *after* the panel is completely visible, so the animation will behave a lot more consistently.  This has the added benefit of also moving the focus of the view when a user clicks on the `+/-` prompt.

**Comment by boveus** [comment]
A couple of additions we can make note of to add later (they are relatively minor).

image

I think we should use the arrows here instead of the +/- to make the behavior consistent across the application.

I also think that we should move the icon change to a .hide/.show [event listener](https://getbootstrap.com/docs/3.3/javascript/#collapse-events).  This way it will change as soon as someone clicks on it instead of after the animation completes.

**Comment by ewilloughby** [comment]
I am a big fan of the slide animation when I click on a search result, it's so smooth and the view port positioning looks great!  This all works really well from my testing, great job.

**Pull request merged**
