### PR TITLE
Let regular users add works

### PR DESCRIPTION
**Pull request by ewilloughby**
@boveus Hey Brandon, this commit is to make it so that once again a regular (non-admin) user can add works.

### CODE REVIEW

**Comment by boveus** [comment]
Why are we allowing non-admin users to create works?  I feel like that is a functionality that should be restricted to administrative users.  Did Jeremy or Kathryn request this?

**Comment by ewilloughby** [comment]
@boveus Regular users should be able to create works and edit metadata of existing works, they just can't do administrative things like edit roles, etc.  We have many staff that will need to use samvera to add things, but all of them should not need to be admins to complete their work.

**Comment by jeremytbright** [comment]
For clarity, now that we've decided on some better vocab: admins and uploaders will both need to upload works. All uploader works will need to be approved by admins. Visitors should never be able to add works on their own (or sign up for accounts). Does that make it clearer?

**Comment by boveus** [comment]
hey @jeremytbright, that sounds good.  I don't think we need a formal user story or anything for this.  I was looking at adding a new feature today and this one looks as good as any. I will get an upload user role made with a sample user account assigned to it.  How does this look for the uploader role's permissions:
```
Admin
----
CAN do any CRUD action on a work
CAN view admin dashboard and use any admin functionality
----

Uploader
----
CAN create, edit (?) any work
CANNOT destroy(delete) any work or access any admin functionality
----

User
----
CAN view any work
CANNOT do any CRUD action.
----

**Comment by ewilloughby** [comment]
@boveus @jeremytbright I am not clear on the User role?  Are we going to have any users who can login who cannot add works? In the broken down description above, it seems to be that User should also have CANNOT login, or is that wrong?  If not, then it seems like an Uploader's abilities should be considered the base "user" abilities for anyone who can login.  I'm still not clear why our ability configuration was changed so that only admins could add works in the first place.  This was to fix that.

**Comment by jeremytbright** [comment]
Sorry to take so long to get back to this! Yes, that looks right - admin/uploader/unreg user.

**Pull request closed without merging**
